### ISSUE TITLE
Link the results!

### ISSUE THREAD

**Issue by fischerq** [scpeters/benchmark#1]
It would be great to mention your presentation of the results (which I found [here](http://www.osrfoundation.org/wordpress2/wp-content/uploads/2015/04/roscon2014_scpeters.pdf)) in the readme.

When I first came across the repo I thought this looks great, but didn't want to go to the lengths of actually setting up/running the benchmarks. I just found the presentation later via Google, would be helpful to have it included here!

**Comment by scpeters** [comment]
Thanks for the idea! I've updated the readme accordingly.
