### ISSUE TITLE
The jupyter notebook for plotting result seems outdated

### ISSUE THREAD

**Issue by yaswanth1701** [scpeters/benchmark#10]
System: Ubuntu 20.04 
The [jupyter notebook](https://github.com/scpeters/benchmark/blob/master/boxes_results.ipynb) version looks outdated.
 
<img width="669" alt="notebook" src="https://github.com/scpeters/benchmark/assets/92177410/6d2556db-d3d2-4d5c-8d84-50f1e618211a">

**Comment by shivangvijay** [comment]
I think the issue is due to the nbformat version. Let me change it to v4.

**Comment by yaswanth1701** [comment]
Yeah I changed it, it fixed the issue. Maybe I will open a PR.

**Comment by yaswanth1701** [comment]
Oh you open one I didn't saw that. Cool !!

**Comment by mabelzhang** [comment]
Yes! I saw that with another Python notebook as well. Thanks!
