### ISSUE TITLE
Logging test results

### ISSUE THREAD

**Issue by mabelzhang** [scpeters/benchmark#24]
Currently, ground truths are baked into test cases. Test code is simulator-dependent.

For portability to other simulators, test results should be written to log files. It could be as simple as csv files.
The expected format should be documented, e.g. column headings.

Starting point: see existing csv files https://github.com/scpeters/benchmark/tree/master/test_results

Consider: Writing to log consumption computation time. Could save the test results to memory, and write csv only at the end.

**Comment by scpeters** [comment]
> Starting point: see existing csv files https://github.com/scpeters/benchmark/tree/master/test_results

I think the test_results csv files are a useful reference, but they contain postprocessed data with a statistical overview of the results of each test. I think it would be easier to reproduce with other simulators if the log file includes the raw data with multiple timesteps for each test run. For example, the [boxes_description](https://github.com/scpeters/benchmark/blob/master/boxes_description.ipynb?short_path=38019af#L173-L189) includes an analytical solution for the position of the center of mass of each box (a parabolic function of time). I would recommend defining an expected data format (such as csv or [mcap](https://mcap.dev/)) including specific variables relevant to each test for multiple timesteps. We can then write a post-processing script to calculate different performance benchmarks based on this intermediate data.

If a given simulator already has a logging format, it may be easiest to record dynamic states in the existing format and then write a script to convert to the expected result format for this benchmark.

For the `boxes` test in particular, I think the following fields should be logged:

For a specified simulation time interval `[t0, t1, t2, ... tN]`:

* simulation time
* cumulative computation time
* for each box:
    - pose of box relative to world frame
    - linear velocity of box relative to world frame, expressed in world frame
    - angular velocity of box relative to world frame, expressed in world frame

Several helper functions are used in Gazebo to compute angular momentum and total energy of a link, but these can be reproduced from the pose and velocities of a box that matches the inertial parameters in the problem description.

We could consider allowing extra fields to be added to the file format, which may help with debugging the post-processing script.
