### ISSUE TITLE
libtbb.so -> DSO missing from command line

### ISSUE THREAD

**Issue by shivangvijay** [scpeters/benchmark#8]
System:- Ubuntu 22.04 LTS
![libtbb](https://github.com/scpeters/benchmark/assets/36565630/d69791ce-d04c-48f0-a078-f8b7e5f906a7)

**Comment by shivangvijay** [comment]
The problem is solve after updating CMakeLists.txt:-  target_link_libraries(gtest_main gtest tbb)

**Comment by scpeters** [comment]
fixed by #9
